apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlproject1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlproject1
  template:
    metadata:
      labels:
        app: mlproject1
    spec:
      containers:
        - name: my-container
          image: wajeeta/docker-hellow-world-new:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlproject1-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlproject1
  template:
    metadata:
      labels:
        app: mlproject1
    spec:
      containers:
        - name: my-container
          image: wajeeta/docker-gs-ping:latest

